blueprints/generador.py
from pydoc import splitdoc
from flask import Blueprint, render_template, abort, request, session, Markup
from jinja2 import TemplateNotFound
from .gen_java_plsql import generar_call_plsql, generar_seteo_parametros, generar_java_plsql_constantes, gen_pl_cursor_out

generador_page = Blueprint('generador_page', __name__,
                           template_folder='templates')

tp_campo_formulario_v = '''
<div className="mb-3">
    <label htmlFor="{id}" className="form-label">{label}</label>
    <input type="{tipo}" className="form-control" id="{id}" name="{id}" aria-describedby="{id}Help" value=[[[valoresFormulario.{id}]]] onChange=[[[gestionarCambioValor]]] />
    <div id="{id}Help" className="form-text"></div>
</div>
'''

tp_campo_formulario_h = '''
<div className="row mb-3">
    <label className="col-sm-2 col-form-label" htmlFor="{id}">{label}</label>
    <div className="col-sm-10">
        <input type="{tipo}" className="form-control" id="{id}" name="{id}" aria-describedby="{id}Help" value=[[[valoresFormulario.{id}]]] onChange=[[[gestionarCambioValor]]] />
        <div id="{id}Help" className="form-text"></div>
    </div>
</div>
'''

tp_tabla = '''<table className="table table-hover">
  <thead>
    <tr>
     {cabecera}
    </tr>
  </thead>
  <tbody>
    <tr>
      {datos}
    </tr>
    <tr>
      {datos}
    </tr>
  </tbody>
</table>'''

tp_react_formulario_manejadores = '''function gestionarEnvioFormulario(evt) {
    evt.preventDefault();
    // Aquí puedes usar values para enviar la información
    console.log(valoresFormulario);
}
function gestionarCambioValor(evt) {
    /*
      evt.target es el elemento que ejecuto el evento
      name identifica el input y value describe el valor actual
    */
    const { target } = evt;
    const { name, value } = target;
    /*
      Este snippet:
      1. Clona el estado actual
      2. Reemplaza solo el valor del
         input que ejecutó el evento
    */
    const newValoresFormulario = { ...valoresFormulario, [name]: value };
    // Sincroniza el estado de nuevo
    setValoresFormulario(newValoresFormulario);
    console.log(newValoresFormulario);
}'''


tp_react_componente = '''
/* {nombre_archivo}.page.js */
import [[[useState]]] from "react";
function {nombre_archivo}() [[[
    return (
        <h1>{componente}</h1>
        );
]]]
export default {nombre_archivo};

'''


@generador_page.route('/generar/javaplsql/cursor', methods=['POST', 'GET'])
def java_plsql_cursor():
    parametros_plsql_cursor = ''
    codigo_final_generado = ''

    if request.method == 'POST':
        parametros_plsql_cursor = request.form['parametros_plsql_cursor']

        session['parametros_plsql_cursor'] = parametros_plsql_cursor
        lineas = parametros_plsql_cursor.splitlines()

        codigo_final_generado += gen_pl_cursor_out(lineas)

    else:
        if 'parametros_plsql_cursor' in session:
            parametros_plsql_cursor = session['parametros_plsql_cursor']
    return render_template('generar-java-plsql-cursor.html',
                           parametros_plsql_cursor=parametros_plsql_cursor,
                           codigo_final_generado=codigo_final_generado)


@generador_page.route('/generar/javaplsql', methods=['POST', 'GET'])
def java_plsql():
    parametros_plsql = ''
    codigo_final_generado = ''

    if request.method == 'POST':
        nombre_clase_componente = request.form['nombre_clase_componente']
        nombre_plsql = request.form['nombre_plsql']
        parametros_plsql = request.form['parametros_plsql']
        session['parametros_plsql'] = parametros_plsql
        lineas = parametros_plsql.splitlines()
        codigo_final_generado += generar_java_plsql_constantes(lineas)

        codigo_final_generado += generar_call_plsql(
            nombre_plsql) + '\n'

        codigo_final_generado += generar_seteo_parametros(lineas)

    else:
        if 'parametros_plsql' in session:
            parametros_plsql = session['parametros_plsql']
    return render_template('generar-java-plsql.html',
                           parametros_plsql=parametros_plsql,
                           codigo_final_generado=codigo_final_generado)


def desamblar_campo(linea):
    linea = linea.replace('  ', ' ')
    array = linea.split(';')
    identificador = str(array[0]).lower().replace(' ', '_')
    etiqueta = str(array[0]).capitalize()
    archivo = str(array[0]).title()

    tipo = array[1] if len(array) > 1 else 'text'

    return identificador, tipo, etiqueta, archivo


@generador_page.route('/generar/componente', methods=['POST', 'GET'])
def componente():
    lista_componentes = '''Usuario Registro
Usuario Actualizacion
Usuario Asociar Rol'''
    componentes_generados = []
    try:
        if request.method == 'POST':
            lista_componentes = request.form['lista_componentes']
            session['lista_componentes'] = lista_componentes
            lineas = lista_componentes.splitlines()
            for item in lineas:
                ide, tipo, label, filename = desamblar_campo(item)
                print()
                archivo = filename.replace(' ', '')
                componente_definicion = tp_react_componente.format(
                    componente=label, nombre_archivo=archivo)
                componente_definicion = reemplazar_llave_react(
                    componente_definicion)
                componentes_generados.append(componente_definicion)

        else:
            if 'lista_componentes' in session:
                lista_componentes = session['lista_componentes']

        return render_template('generar-componente.html', componentes_generados=componentes_generados,
                               lista_componentes=lista_componentes)
    except TemplateNotFound:
        abort(404)


@generador_page.route('/generar/tablas', methods=['POST', 'GET'])
def tablas():
    text_area_data = 'ingresar csv'
    codigo_generado = ''
    html_generado = ''
    try:
        if request.method == 'POST':

            text_area_data = request.form['text_area_data']
            session['text_area_data'] = text_area_data
            print(text_area_data)

            lineas = text_area_data.splitlines()
            tabla_cabecera = ''
            tabla_td = ''
            for item in lineas:
                ide, tipo, label, nombre = desamblar_campo(item)

                tabla_cabecera += '<th scope="col">{}</th>'.format(label)
                tabla_td += '<td>{}</td>'.format('item')

            codigo_generado = tp_tabla.format(
                cabecera=tabla_cabecera, datos=tabla_td)

            html_generado = generar_codigo_markup(codigo_generado)

        else:
            if 'text_area_data' in session:
                text_area_data = session['text_area_data']

        return render_template('generar-tabla.html', codigo_generado=codigo_generado,
                               text_area_data=text_area_data, html_generado=html_generado)
    except TemplateNotFound:
        abort(404)


@generador_page.route('/generar/formulario', methods=['POST', 'GET'])
def formularios():
    text_area_data = 'ingresar csv'
    codigo_generado = ''
    tipo_form = 'V'
    arreglo_id_campos = []
    try:
        if request.method == 'POST':

            text_area_data = request.form['text_area_data']
            tipo_form = request.form['tipo_form']
            session['text_area_data'] = text_area_data
            print(text_area_data)

            lineas = text_area_data.splitlines()
            codigo_generado = []
            arreglo_id_campos = []
            for item in lineas:
                ide, tipo, label, nombre = desamblar_campo(item)
                codigo_generado.append(generar_html_input(
                    ide, tipo, label, tipo_form))
                arreglo_id_campos.append('''{id}: "",'''.format(id=ide))

        else:
            if 'text_area_data' in session:
                text_area_data = session['text_area_data']

        codigo_generado = generar_formulario_html(codigo_generado)
        html_generado = generar_codigo_markup(codigo_generado)
        react_generado = generar_react_data_formulario(arreglo_id_campos)

        return render_template('generar-formulario.html', codigo_generado=codigo_generado, tipo_form=tipo_form,
                               text_area_data=text_area_data,
                               html_generado=html_generado,
                               react_generado=react_generado,
                               react_manejadores=tp_react_formulario_manejadores)
    except TemplateNotFound:
        abort(404)


def generar_html_input(ide, tipo, label, tipo_form):
    html_input = ''
    if tipo_form == 'V':
        html_input = tp_campo_formulario_v.format(
            id=ide, tipo=tipo, label=label)
    else:
        html_input = tp_campo_formulario_h.format(
            id=ide, tipo=tipo, label=label)
    html_input = reemplazar_llave_react(html_input)
    return html_input


def generar_formulario_html(arreglo_codigos):
    html = '<form onSubmit={gestionarEnvioFormulario}>'
    for item in arreglo_codigos:
        html += item
    html += '''<button className="btn btn-info">Enviar Formulario</button>
</form>'''
    return html


def generar_codigo_markup(codigo_generado):
    codigo_generado = codigo_generado.replace('className=', 'class=')
    html_generado = Markup(codigo_generado)
    return html_generado


def reemplazar_llave_react(codigo_con_llaves):
    codigo_con_llaves = codigo_con_llaves.replace('[[[', '{')
    codigo_con_llaves = codigo_con_llaves.replace(']]]', '}')
    return codigo_con_llaves


def generar_react_data_formulario(arreglo_codigos):
    react = "const [valoresFormulario, setValoresFormulario] = useState({"
    for item in arreglo_codigos:
        react += item
    react += "});"
    return react


@generador_page.route('/generar/grilla', methods=['POST', 'GET'])
def grilla():
    codigo_sin_formato = ''
    html_generado = ''
    grilla_alto = 3
    grilla_ancho = 2
    try:

templates/autor.html
{% extends 'base.html' %} {% block content %}
<div class="px-4 py-5 my-5 text-center">
  <img
    class="d-block mx-auto mb-4"
    src="https://flask.palletsprojects.com/en/2.1.x/_images/flask-logo.png"
    alt=""
    width="72"
  />
  <h1 class="display-5 fw-bold">Prototipo</h1>
  <div class="col-lg-6 mx-auto">
    <p class="lead mb-4">
      Generador de Código fuente para desarrollo de aplicaciones con React
    </p>
    <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
      <!-- Button trigger modal -->
      <button
        type="button"
        class="btn btn-primary"
        data-bs-toggle="modal"
        data-bs-target="#staticBackdrop"
      >
        Weena
      </button>
      <button type="button" class="btn btn-outline-secondary btn-lg px-4">
        Yupi!
      </button>
    </div>
  </div>
</div>

<!-- Modal -->
<div
  class="modal fade"
  id="staticBackdrop"
  data-bs-backdrop="static"
  data-bs-keyboard="false"
  tabindex="-1"
  aria-labelledby="staticBackdropLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Weena</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">Weenardo</div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Weena
        </button>
        <button type="button" class="btn btn-primary">Weena</button>
      </div>
    </div>
  </div>
</div>

{% endblock %} {% block codigo_scripts %}
<script>
  $(window).on("load", function () {
    console.log("Cargando pagina denerador de codigo");
  });
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>

    <link
      rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/styles/default.min.css"
    />

    <title>Generador de Códigos</title>

    <!-- Custom styles for this template -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static',filename='base.css') }}"
    />
  </head>
  <body>
    <header
      class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow"
    >
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 text-success" href="#"
        >~/generador</a
      >
      <button
        class="navbar-toggler position-absolute d-md-none collapsed"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#sidebarMenu"
        aria-controls="sidebarMenu"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="w-100 text-success">~/generador de código</div>
    </header>

    <div class="container-fluid">
      <div class="row">
        <nav
          id="sidebarMenu"
          class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse"
        >
          <div class="position-sticky pt-3">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a
                  class="nav-link active"
                  aria-current="page"
                  href="{{ url_for('index') }}"
                >
                  <span data-feather="home"></span>
                  Home
                </a>
              </li>
              <li class="nav-item">
                <a
                  class="nav-link"
                  href="{{ url_for('generador_page.componente') }}"
                >
                  <span data-feather="file"></span>
                  Generar Componente React
                </a>
              </li>
              <li class="nav-item">
                <a
                  class="nav-link"
                  href="{{ url_for('generador_page.formularios') }}"
                >
                  <span data-feather="file"></span>
                  Generar Formulario
                </a>
              </li>
              <li class="nav-item">
                <a
                  class="nav-link"
                  href="{{ url_for('generador_page.grilla') }}"
                >
                  <span data-feather="file"></span>
                  Generar Grilla
                </a>
              </li>

              <li class="nav-item">
                <a
                  class="nav-link"
                  href="{{ url_for('generador_page.tablas') }}"
                >
                  <span data-feather="file"></span>
                  Generar Tabla
                </a>
              </li>
              <li class="nav-item">
                <a
                  class="nav-link"
                  href="{{ url_for('generador_page.java_plsql') }}"
                >
                  <span data-feather="file"></span>
                  Generar Java PLSQL
                </a>
              </li>
              <li class="nav-item">
                <a
                  class="nav-link"
                  href="{{ url_for('generador_page.java_plsql_cursor') }}"
                >
                  <span data-feather="file"></span>
                  Generar Java Mapeo Cursor
                </a>
              </li>
            </ul>

            <h6
              class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted"
            >
              <span>Links</span>
              <a class="link-secondary" href="#" aria-label="Add a new report">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a
                  class="nav-link"
                  target="_blank"
                  href="https://getbootstrap.com/docs/5.0/examples/"
                >
                  <span data-feather="file-text"></span>
                  Bootstrap Examples
                </a>
              </li>
              <li class="nav-item">
                <a
                  class="nav-link"
                  target="_blank"
                  href="https://getbootstrap.com/docs/5.0/getting-started/introduction/"
                >
                  <span data-feather="file-text"></span>
                  Bootstrap Documentación
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div
            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"
          >
            <h1 class="h2">Generador de Códigos</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group me-2">
                <button type="button" class="btn btn-sm btn-outline-secondary">
                  Nada
                </button>
                <button type="button" class="btn btn-sm btn-outline-secondary">
                  Nada
                </button>
              </div>
              <button
                type="button"
                class="btn btn-sm btn-outline-secondary dropdown-toggle"
              >
                <span data-feather="calendar"></span>
                Nada
              </button>
            </div>
          </div>

          <div class="container">
            {% for message in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
            {% endfor %}

            <!-- ACA VA EL CONTENIDO -->
            {% block content %}{% endblock %}
          </div>
        </main>
      </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js"></script>

    <script>
      feather.replace();
      hljs.highlightAll();
    </script>

    {% block codigo_scripts %}{% endblock %}
  </body>
</html>

templates/formulario.html
{% extends 'base.html' %} {% block content %}
<form class="row g-3 needs-validation" novalidate>
  <div class="col-md-4">
    <label for="validationCustom01" class="form-label">First name</label>
    <input
      type="text"
      class="form-control"
      id="validationCustom01"
      value="Mark"
      required
    />
    <div class="valid-feedback">Looks good!</div>
  </div>
  <div class="col-md-4">
    <label for="validationCustom02" class="form-label">Last name</label>
    <input
      type="text"
      class="form-control"
      id="validationCustom02"
      value="Otto"
      required
    />
    <div class="valid-feedback">Looks good!</div>
  </div>
  <div class="col-md-4">
    <label for="validationCustomUsername" class="form-label">Username</label>
    <div class="input-group has-validation">
      <span class="input-group-text" id="inputGroupPrepend">@</span>
      <input
        type="text"
        class="form-control"
        id="validationCustomUsername"
        aria-describedby="inputGroupPrepend"
        required
      />
      <div class="invalid-feedback">Please choose a username.</div>
    </div>
  </div>
  <div class="col-md-6">
    <label for="validationCustom03" class="form-label">City</label>
    <input type="text" class="form-control" id="validationCustom03" required />
    <div class="invalid-feedback">Please provide a valid city.</div>
  </div>
  <div class="col-md-3">
    <label for="validationCustom04" class="form-label">State</label>
    <select class="form-select" id="validationCustom04" required>
      <option selected disabled value="">Choose...</option>
      <option>...</option>
    </select>
    <div class="invalid-feedback">Please select a valid state.</div>
  </div>
  <div class="col-md-3">
    <label for="validationCustom05" class="form-label">Zip</label>
    <input type="text" class="form-control" id="validationCustom05" required />
    <div class="invalid-feedback">Please provide a valid zip.</div>
  </div>
  <div class="col-12">
    <div class="form-check">
      <input
        class="form-check-input"
        type="checkbox"
        value=""
        id="invalidCheck"
        required
      />
      <label class="form-check-label" for="invalidCheck">
        Agree to terms and conditions
      </label>
      <div class="invalid-feedback">You must agree before submitting.</div>
    </div>
  </div>
  <div class="col-12">
    <button class="btn btn-primary" type="submit">Submit form</button>
  </div>
</form>

{% endblock %}

templates/generar-componente.html
{% extends 'base.html' %} {% block content %}

<form method="post">
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Entrada</label>
    <div id="emailHelp" class="form-text">Listado de Componentes</div>
    <textarea rows="4" cols="50" name="lista_componentes" class="form-control">
{{ request.form['lista_componentes'] or lista_componentes }}</textarea
    >
  </div>

  <button type="submit" class="btn btn-primary">Generar</button>
</form>

<h3 class="mt-3">Resultado</h3>
<hr />

<!-- For loop logic of jinja template -->
{%for item in componentes_generados %}
<pre><code class="language-javascript">{{item}}</code></pre>
{%endfor%}

<p></p>
{% endblock %} {% block codigo_scripts %}
<script>
  $(window).on("load", function () {
    console.log("Cargando pagina denerador de codigo");
  });
</script>
{% endblock %}

templates/generar-formulario.html
{% extends 'base.html' %} {% block content %}

<form method="post">
  <div class="mb-3">
    <label for="tipo_form" class="form-label">Tipo Formulario</label>
    <select
      class="form-select"
      id="tipo_form"
      name="tipo_form"
      aria-label="Default select example"
    >
      <option value="H">Horizontal</option>
      <option selected value="V">Vertical</option>
    </select>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Entrada</label>
    <div id="emailHelp" class="form-text">nombre_campo:tipo</div>
    <textarea rows="4" cols="50" name="text_area_data" class="form-control">
{{ request.form['text_area_data'] or text_area_data }}</textarea
    >
  </div>

  <button type="submit" class="btn btn-primary">Generar</button>
</form>

<h3 class="mt-3">Resultado</h3>
<hr />
<pre><code class="language-javascript">
{{react_generado}}

{{react_manejadores}}</code></pre>
<hr />

<pre><code class="language-html">{{codigo_generado}}</code></pre>

<hr />

{{html_generado}}

<hr />

{% endblock %} {% block codigo_scripts %}
<script>
  $(window).on("load", function () {
    console.log("Cargando pagina denerador de codigo");
    $("#tipo_form").val("{{ request.form['tipo_form'] or tipo_form }}");
  });
</script>
{% endblock %}

templates/generar-grilla.html
{% extends 'base.html' %} {% block content %}

<form method="post">
  <div class="mb-3">
    <label for="grilla_ancho" class="form-label">Grilla Ancho</label>
    <input
      type="text"
      class="form-control"
      id="grilla_ancho"
      name="grilla_ancho"
      aria-describedby="grilla_anchoHelp"
      value="{{ request.form['grilla_ancho'] or grilla_ancho }}"
    />
  </div>
  <div class="mb-3">
    <label for="grilla_alto" class="form-label">Grilla Alto</label>
    <input
      type="text"
      class="form-control"
      id="grilla_alto"
      name="grilla_alto"
      aria-describedby="grilla_altoHelp"
      value="{{ request.form['grilla_alto'] or grilla_alto }}"
    />
  </div>

  <button type="submit" class="btn btn-primary">Generar</button>
</form>

<h3 class="mt-3">Resultado</h3>
<hr />
<pre><code class="language-html">{{ codigo_sin_formato }}</code></pre>

<hr />

<div class="container">{{html_generado}}</div>
{% endblock %} {% block codigo_scripts %}
<script>
  $(window).on("load", function () {
    console.log("Cargando pagina denerador de codigo");
  });
</script>
{% endblock %}

templates/generar-java-plsql-cursor.html
{% extends 'base.html' %} {% block content %}

<form method="post">
  <div class="mb-3">
    <label for="nombre_clase_componente" class="form-label"
      >public class
    </label>
    <input
      type="text"
      class="form-control"
      id="nombre_clase_componente"
      name="nombre_clase_componente"
      aria-describedby="nombre_clase_componenteHelp"
      value="{{ request.form['nombre_clase_componente'] or nombre_clase_componente }}"
    />
    <div class="form-text text-muted">nombre de la clase</div>
  </div>

  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label"
      >Declaración Campos a Mapear</label
    >

    <textarea
      rows="4"
      cols="50"
      name="parametros_plsql_cursor"
      class="form-control"
    >
{{ request.form['parametros_plsql_cursor'] or parametros_plsql_cursor }}</textarea
    >
    <div id="emailHelp" class="form-text">
      Tipos soportados: NUMERIC, VARCHAR,CURSOR
    </div>
  </div>

  <button type="submit" class="btn btn-primary">Generar</button>
</form>

<h3 class="mt-3">Resultado</h3>
<hr />
<pre><code class="language-java">{{ codigo_final_generado }}</code></pre>

<hr />

<div class="container">{{html_generado}}</div>
{% endblock %} {% block codigo_scripts %}
<script>
  $(window).on("load", function () {
    console.log("Cargando pagina denerador de codigo");
  });
</script>
{% endblock %}

templates/generar-java-plsql.html
{% extends 'base.html' %} {% block content %}

<form method="post">
  <div class="mb-3">
    <label for="nombre_clase_componente" class="form-label"
      >public class
    </label>
    <input
      type="text"
      class="form-control"
      id="nombre_clase_componente"
      name="nombre_clase_componente"
      aria-describedby="nombre_clase_componenteHelp"
      value="{{ request.form['nombre_clase_componente'] or nombre_clase_componente }}"
    />
    <div class="form-text text-muted">nombre de la clase</div>
  </div>
  <div class="mb-3">
    <label for="nombre_plsql" class="form-label">Declaración del PLSQL</label>
    <input
      type="text"
      class="form-control"
      id="nombre_plsql"
      name="nombre_plsql"
      aria-describedby="nombre_plsqlHelp"
      value="{{ request.form['nombre_plsql'] or nombre_plsql }}"
    />
    <div class="form-text text-muted">esquema.paquete.procedimiento(?,?,?)</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label"
      >Parametros del Procedimiento</label
    >
    <div id="emailHelp" class="form-text">Nombre_Parametro;I/O;Tipo</div>
    <textarea rows="4" cols="50" name="parametros_plsql" class="form-control">
{{ request.form['parametros_plsql'] or parametros_plsql }}</textarea
    >
    <div id="emailHelp" class="form-text">
      Tipos soportados: NUMERIC, VARCHAR,CURSOR
    </div>
  </div>

  <button type="submit" class="btn btn-primary">Generar</button>
</form>

<h3 class="mt-3">Resultado</h3>
<hr />
<pre><code class="language-java">{{ codigo_final_generado }}</code></pre>

<hr />

<div class="container">{{html_generado}}</div>
{% endblock %} {% block codigo_scripts %}
<script>
  $(window).on("load", function () {
    console.log("Cargando pagina denerador de codigo");
  });
</script>
{% endblock %}

templates/generar-tabla.html
{% extends 'base.html' %} {% block content %}

<form method="post">
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Entrada</label>
    <div id="emailHelp" class="form-text">Listado de campos</div>
    <textarea rows="4" cols="50" name="text_area_data" class="form-control">
{{ request.form['text_area_data'] or text_area_data }}</textarea
    >
  </div>

  <button type="submit" class="btn btn-primary">Generar</button>
</form>

<h3 class="mt-3">Resultado</h3>
<hr />

<pre><code class="language-html">{{codigo_generado}}</code></pre>

<hr />

{{html_generado}}
<p></p>
{% endblock %} {% block codigo_scripts %}
<script>
  $(window).on("load", function () {
    console.log("Cargando pagina denerador de codigo");
  });
</script>
{% endblock %}